import '@defs'
import 'standard'
import 'helpers/global'
import 'hooks/global'
import 'features/ecs/global'
import 'controllers/WasdController/global'
import 'controllers/ThirdPersonCameraController/global'

import 'libs/react/global'
import 'libs/three/global'
